Repository K-Roum/FE, pull requests merged in 2025-06, with the labels that each got.

#14 [feat]create review section & bookmark connect
  src/components/ui/searchPage/DetailModal.tsx
  src/components/ui/searchPage/ReviewForm.tsx
Labels: feat

#20 [feat] mypage
  src/components/ui/myPage/ProfileInfo.jsx
  src/components/ui/myPage/ReviewPreview.jsx
  src/components/ui/myPage/Sidebar.jsx
  src/components/ui/myPage/WishlistPreview.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPageLayout.jsx
  src/pages/MyPage/ProfileEditPage.jsx
  src/pages/MyPage/ReviewListPage.jsx
  src/pages/MyPage/WishlistPage.jsx
Labels: feat

#23 mypage-code-modify
  src/Routes.jsx
  src/components/common/Header.jsx
  src/components/ui/loginPage/loginApi.ts
  src/components/ui/myPage/Sidebar.jsx
Labels: modify

#24 [feat][refactor]modify hashtag random create add
  src/Routes.jsx
  src/components/ui/homePage/TrendingHashtags.jsx
  src/components/ui/homePage/TrendingHashtags.tsx
  src/components/ui/searchPage/DetailModal.tsx
  src/components/ui/searchPage/SearchResultCard.jsx
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/ru.json
  src/locales/zh.json
  src/model/PlaceDetailModel.ts
  src/pages/Home/HomePage.jsx
  src/pages/Home/hooks/storage.js
  src/pages/Search/SearchPage.tsx
Labels: bug, modify, feat, fix

#27 01-mypage-modify
  src/components/ui/myPage/ReviewPreview.jsx
  src/components/ui/myPage/Sidebar.jsx
  src/components/ui/myPage/WishlistPreview.jsx
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/ru.json
  src/locales/zh.json
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/ProfileEditPage.jsx
  src/pages/MyPage/ReviewListPage.jsx
  src/pages/MyPage/WishlistPage.jsx
  src/pages/Signup/SignupPage.jsx
Labels: modify

#29 [fix]hsh/25 fix modify bookmark review date
  src/components/ui/homePage/SearchSection.tsx
  src/components/ui/searchPage/DetailModal.tsx
  src/components/ui/searchPage/SearchResultCard.jsx
  src/pages/Search/SearchPage.tsx
Labels: fix

#33 guhyoen/modify-mypage2
  src/components/ui/myPage/ReviewPreview.jsx
  src/components/ui/myPage/WishlistPreview.jsx
  src/components/ui/myPage/myPageDetailModal.tsx
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/ru.json
  src/locales/zh.json
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPageLayout.jsx
  src/pages/MyPage/ReviewListPage.jsx
  src/pages/MyPage/WishlistPage.jsx
  tailwind.config.js
Labels: modify, feat

#34 [fix]searchPrompt 오류수정
  src/locales/de.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/ja.json
  src/locales/ru.json
  src/locales/zh.json
Labels: fix

#36 [fix] error fix
  src/locales/ja.json
Labels: fix

#39 review_bookmark_modify
  src/components/ui/myPage/myPageDetailModal.tsx
  src/components/ui/searchPage/ReviewForm.tsx
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/ru.json
  src/locales/zh.json
  src/pages/MyPage/ReviewListPage.jsx
Labels: modify, feat

#41 [fix][refactor]hsh/37 fix bookmark error
  .gitignore
  src/components/ui/homePage/SearchSection.tsx
  src/components/ui/homePage/TrendingHashtags.tsx
  src/components/ui/searchPage/DetailModal.tsx
  src/components/ui/searchPage/MapComponent.tsx
  src/components/ui/searchPage/SearchResultCard.tsx
  src/pages/Search/SearchPage.tsx
  src/services/SearchApi.ts
  src/services/reviewApi.ts
Labels: bug, modify, feat, fix, refactor

#47 프로필편집/회원가입언어설정/시작페이지언어설정 코드수정
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/ru.json
  src/locales/zh.json
  src/pages/LanguageSelect.jsx
  src/pages/Login/LoginPage.jsx
  src/pages/MyPage/ProfileEditPage.jsx
  src/pages/Signup/SignupPage.jsx
Labels: modify, feat, refactor

#48 [modify]hsh/43 modify search section
  src/components/ui/homePage/FeaturedContent.jsx
  src/components/ui/homePage/SearchSection.tsx
  src/components/ui/searchPage/MapComponent.tsx
  src/pages/Search/SearchPage.tsx
Labels: modify

#50 마이페이지모달에서 리뷰작성 및 실시간 반영
  src/components/ui/myPage/ProfileInfo.jsx
  src/components/ui/myPage/myPageDetailModal.tsx
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/ru.json
  src/locales/zh.json
Labels: modify, feat

#56 최종 디버깅
  public/assets/deLoginLogo.png
  public/assets/enLoginLogo.png
  public/assets/esLoginLogo.png
  public/assets/frLoginLogo.png
  public/assets/jaLoginLogo.png
  public/assets/ruLoginLogo.png
  public/assets/zhLoginLogo.png
  src/components/ui/loginPage/findIdApi.ts
  src/components/ui/myPage/ProfileInfo.jsx
  src/components/ui/myPage/myPageDetailModal.tsx
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/ru.json
  src/locales/zh.json
  src/pages/Login/FindAccountPage.jsx
  src/pages/Login/FindIdPage.jsx
  src/pages/Login/LoginPage.jsx
  src/pages/Login/ResetPasswordPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPageLayout.jsx
  src/pages/MyPage/ProfileEditPage.jsx
  src/pages/MyPage/ReviewListPage.jsx
  src/pages/MyPage/WishlistPage.jsx
  src/pages/Signup/SignupCompletePage.jsx
  src/pages/Signup/SignupPage.jsx
  src/utils/languageUtils.js
Labels: modify, fix

#55 [fix] hsh/54 fix i18n error
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/ru.json
  src/locales/zh.json
  tailwind.config.js
Labels: fix
